"""
Write docs/guide/species_summaries.typ (the guide's species appendix) from
meta/species_summaries.tsv. Run from the repository root after
`ploidyspec panel --results results --outdir meta`.
"""

import csv
import os
from collections import OrderedDict

OUT = "docs/guide/species_summaries.typ"

# species without a meta/literature_ploidy.tsv entry
EXTRA = {
    "SchCurv1": ("Schizothorax curvilabiatus", "4n = 98 (Xie et al., 2026)"),
    "SchYoun1": ("Schizopygopsis younghusbandi", "4n = 90 (Xie et al., 2026)"),
    "lpTriTurg1_A": ("Triticum turgidum, A subgenome", "2n = 4x = 28 (AABB); A subgenome run on its own"),
    "lpTriTurg1_B": ("Triticum turgidum, B subgenome", "2n = 4x = 28 (AABB); B subgenome run on its own"),
}
TITLES = OrderedDict(ploidy="Ploidy", origin_like_structure="Auto- or allo-like",
                     te_markers="TE markers", rediploidization="Rediploidization")
COLOURS = {"high": "#2f855a", "medium": "#b7791f", "low": "#c05621", "not assessable": "#a0aec0"}


def names():
    out = {}
    with open("meta/meta.tsv") as f:
        for row in csv.reader(f, delimiter="\t"):
            if len(row) > 2 and row[1]:
                out[row[1]] = (os.path.basename(row[2]).replace("_", " "), "")
    with open("meta/literature_ploidy.tsv") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            count = (r.get("literature_chrom_number") or "").strip()
            out[r["species"]] = (r.get("scientific_name") or out.get(r["species"], ("", ""))[0], count)
    out.update(EXTRA)
    return out


def s(text):
    """A Typst string literal: shown verbatim, no markup."""
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    rows = OrderedDict()
    with open("meta/species_summaries.tsv") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            rows.setdefault(r["species"], {})[r["question"]] = r
    nm = names()
    out = ['// generated by docs/guide/make_species_appendix.py from meta/species_summaries.tsv',
           '#let badge(conf, col) = box(fill: rgb(col), inset: (x: 4pt, y: 1.5pt), radius: 3pt,',
           '  text(size: 7.5pt, fill: white, weight: "bold", conf))',
           '#let card(code, name, lit, items) = block(breakable: false, width: 100%, inset: 8pt,',
           '  radius: 4pt, stroke: 0.5pt + rgb("#cbd5e0"), below: 8pt, [',
           '  #text(weight: "bold", fill: rgb("#2b6cb0"), code) #h(4pt) #emph(name)',
           '  #if lit != "" [#h(1fr) #text(size: 8pt, fill: rgb("#4a5568"))[literature: #lit]]',
           '  #v(-2pt)',
           '  #grid(columns: (2.6cm, 1fr), row-gutter: 5pt, column-gutter: 6pt, ..items)',
           '])', '']
    for sp, qs in sorted(rows.items(), key=lambda kv: kv[0].lower()):
        name, lit = nm.get(sp, ("", ""))
        if len(lit) > 70:
            lit = lit[:67].rstrip() + "..."
        items = []
        for q, title in TITLES.items():
            r = qs.get(q)
            if not r:
                continue
            col = COLOURS.get(r["confidence"], "#a0aec0")
            items.append(f'  [#text(size: 8.5pt, weight: "bold", {s(title)}) \\ #badge({s(r["confidence"])}, {s(col)})],')
            ev = f' \\ #text(size: 7.5pt, fill: rgb("#718096"), {s(r["evidence"])})' if r["evidence"] else ""
            items.append(f'  [#text(size: 8.8pt, {s(r["answer"])}){ev}],')
        out.append(f'#card({s(sp)}, {s(name)}, {s(lit)}, (')
        out += items
        out.append('))')
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUT}: {len(rows)} species")


if __name__ == "__main__":
    main()
