// generated by docs/guide/make_species_appendix.py from meta/species_summaries.tsv
#let badge(conf, col) = box(fill: rgb(col), inset: (x: 4pt, y: 1.5pt), radius: 3pt,
  text(size: 7.5pt, fill: white, weight: "bold", conf))
#let card(code, name, lit, items) = block(breakable: false, width: 100%, inset: 8pt,
  radius: 4pt, stroke: 0.5pt + rgb("#cbd5e0"), below: 8pt, [
  #text(weight: "bold", fill: rgb("#2b6cb0"), code) #h(4pt) #emph(name)
  #if lit != "" [#h(1fr) #text(size: 8pt, fill: rgb("#4a5568"))[literature: #lit]]
  #v(-2pt)
  #grid(columns: (2.6cm, 1fr), row-gutter: 5pt, column-gutter: 6pt, ..items)
])

#card("daBudDavi1", "Buddleja davidii", "2n=76 (x=19)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "4 haplotype copies of each of 19 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (4 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Auto-like (tetrasomic-like): on most chromosomes all copies are about equally close.") \ #text(size: 7.5pt, fill: rgb("#718096"), "19 chromosome numbers assessed: 1 split into lineages, 15 tetrasomic-like, 2 one divergent copy, 1 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Repeat history tracks the lineages on 1 chromosome(s) only.") \ #text(size: 7.5pt, fill: rgb("#718096"), "TE split >= 2 on 1/19 chromosomes (median 1.11); absolute te_marker_fraction 0.1668 (reference only)")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Little sign: 1 chromosome(s) partly split among tetrasomic-like ones.") \ #text(size: 7.5pt, fill: rgb("#718096"), "1 split / 15 tetrasomic-like chromosomes; 1 regional split(s)")],
))
#card("daEupConf1", "Euphrasia confusa", "", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly: only one usable haplotype (22 chromosome numbers). The numbers do form duplicated sets (11 groups of mostly 2 chromosome numbers (genome partition z = 19.2)).") \ #text(size: 7.5pt, fill: rgb("#718096"), "11 groups of mostly 2 chromosome numbers (genome partition z = 19.2)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.") \ #text(size: 7.5pt, fill: rgb("#718096"), "fewer than three copies and nothing to pool")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "TE markers not run for this species.")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.04")],
))
#card("daGalBore1", "Galium boreale", "2n=44 (n=11)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "4 haplotype copies of each of 11 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (4 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Auto-like (tetrasomic-like): on most chromosomes all copies are about equally close.") \ #text(size: 7.5pt, fill: rgb("#718096"), "11 chromosome numbers assessed: 1 split into lineages, 10 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Repeat history does not track the copies' lineages (no within-genome TE contrast).") \ #text(size: 7.5pt, fill: rgb("#718096"), "TE split >= 2 on 0/11 chromosomes (median 1.05); absolute te_marker_fraction 0.1289 (reference only)")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Little sign: 1 chromosome(s) partly split among tetrasomic-like ones.") \ #text(size: 7.5pt, fill: rgb("#718096"), "1 split / 10 tetrasomic-like chromosomes; 1 regional split(s); pair-depth CV 0.00")],
))
#card("daGleHede1", "Glechoma hederacea", "", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 18 chromosome numbers; the numbers form sets of 2 (9 groups of mostly 2 chromosome numbers), so x ≈ 9 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 9 groups of mostly 2 chromosome numbers (genome partition z = 23.8); homeolog distance 0.052 vs unrelated 0.115")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.04). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "18 chromosome numbers assessed: 18 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.2234")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.04")],
))
#card("daInuConz1", "Inula conyza (now Pentanema conyzae)", "2n=32", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 16 chromosome numbers; the numbers form sets of 2 (no accepted pairs, but a balanced two-group partition), so x ≈ 8 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); no accepted pairs, but a balanced two-group partition (8 vs 8, z = 10.6)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from a genome-wide partition (no accepted pairs). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "16 chromosome numbers assessed: 16 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.0166")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("daLatClan1", "Lathraea clandestina", "2n=42 (hexaploid, per one source) though genome-size data suggests...", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 21 chromosome numbers; the numbers form sets of 2 (9 groups of mostly 2 chromosome numbers), so x ≈ 9 and up to 4x relative to x; the sets are nearly as diverged as unrelated chromosomes, so they may be an old (paleo) duplication.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 9 groups of mostly 2 chromosome numbers (genome partition z = 10.6); homeolog distance 0.093 vs unrelated 0.108")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.04). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "18 chromosome numbers assessed: 18 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.2535")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.04")],
))
#card("daLatSqua1", "Lathraea squamaria", "2n=42", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 18 chromosome numbers; the numbers form sets of 2 (8 homeolog pairs covering 89% of numbers), so x ≈ 9 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 8 homeolog pairs covering 89% of numbers; homeolog distance 0.091 vs unrelated 0.117")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.06). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "16 chromosome numbers assessed: 16 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.3198")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.06")],
))
#card("daPilAura1", "Pilosella aurantiaca", "2n=36", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 18 chromosome numbers; the numbers form sets of 2 (9 groups of mostly 2 chromosome numbers), so x ≈ 9 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 9 groups of mostly 2 chromosome numbers (genome partition z = 22.7); homeolog distance 0.036 vs unrelated 0.082")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "One copy apart on most chromosomes, changing haplotype between chromosomes: AAAB-like (one divergent genome copy).") \ #text(size: 7.5pt, fill: rgb("#718096"), "18 chromosome numbers assessed: 0 split into lineages, 0 tetrasomic-like, 18 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.2074")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.11")],
))
#card("daSenVulg1", "Senecio vulgaris", "2n=40", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 20 chromosome numbers; the numbers form sets of 2 (10 groups of mostly 2 chromosome numbers), so x ≈ 10 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 10 groups of mostly 2 chromosome numbers (genome partition z = 12.0); homeolog distance 0.066 vs unrelated 0.094")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.03). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "16 chromosome numbers assessed: 16 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.0413")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.03")],
))
#card("daSonOler1", "Sonchus oleraceus", "uncertain, possible discrepancy", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 16 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable: two haplotypes and no duplicated sets to compare. Diploid-like as assembled.") \ #text(size: 7.5pt, fill: rgb("#718096"), "no homeolog pairs, no genome partition")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.0392")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("dcCerAlpi1", "Cerastium alpinum", "", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 36 chromosome numbers; the numbers form sets of 2 (no accepted pairs, but a balanced two-group partition), so x ≈ 18 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); no accepted pairs, but a balanced two-group partition (16 vs 20, z = 18.9)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from a genome-wide partition (no accepted pairs). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "32 chromosome numbers assessed: 32 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.1979")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("dcHonPepl1", "Honckenya peploides", "", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 34 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable: two haplotypes and no duplicated sets to compare. Diploid-like as assembled.") \ #text(size: 7.5pt, fill: rgb("#718096"), "no homeolog pairs, no genome partition")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.0282")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("ddAraThal4", "Arabidopsis thaliana", "2n=10 (x=5)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly: only one usable haplotype (5 chromosome numbers).") \ #text(size: 7.5pt, fill: rgb("#718096"), "no duplicated sets of chromosome numbers detected")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.") \ #text(size: 7.5pt, fill: rgb("#718096"), "fewer than three copies and nothing to pool")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "TE markers not run for this species.")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("ddEmpNigr1", "Empetrum nigrum", "2n=52 (n=13)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "4 haplotype copies of each of 13 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (4 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): most chromosomes split into two lineages. A long-rediploidized autopolyploid would look the same.") \ #text(size: 7.5pt, fill: rgb("#718096"), "13 chromosome numbers assessed: 10 split into lineages, 0 tetrasomic-like, 3 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Repeat history tracks the lineages on several chromosomes: separate TE histories in the split copies.") \ #text(size: 7.5pt, fill: rgb("#718096"), "TE split >= 2 on 4/13 chromosomes (median 1.73); absolute te_marker_fraction 0.2386 (reference only)")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Split throughout: either rediploidization is complete or the genome was allo-like from the start; these data cannot tell which.") \ #text(size: 7.5pt, fill: rgb("#718096"), "10 split / 0 tetrasomic-like chromosomes; 2 regional split(s)")],
))
#card("ddHesMatr1", "Hesperis matronalis", "2n=24 (most commonly cited tetraploid count)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "4 haplotype copies of each of 6 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (4 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "One copy apart on most chromosomes, changing haplotype between chromosomes: AAAB-like (one divergent genome copy).") \ #text(size: 7.5pt, fill: rgb("#718096"), "6 chromosome numbers assessed: 1 split into lineages, 1 tetrasomic-like, 4 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Repeat history tracks the lineages on several chromosomes: separate TE histories in the split copies.") \ #text(size: 7.5pt, fill: rgb("#718096"), "TE split >= 2 on 1/6 chromosomes (median 1.22); absolute te_marker_fraction 0.0836 (reference only)")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Little sign: 1 chromosome(s) partly split among tetrasomic-like ones.") \ #text(size: 7.5pt, fill: rgb("#718096"), "1 split / 1 tetrasomic-like chromosomes; 0 regional split(s)")],
))
#card("ddHypMacu1", "Hypericum maculatum", "2n=32 (x=8)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "4 haplotype copies of each of 8 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (4 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "One copy apart on most chromosomes, nearly always the same haplotype (HAP1 (8 chromosomes)): most likely an assembly or phasing problem in that haplotype.") \ #text(size: 7.5pt, fill: rgb("#718096"), "8 chromosome numbers assessed: 0 split into lineages, 0 tetrasomic-like, 8 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Repeat content differs between the split copies on several chromosomes, but the split isolates the same odd haplotype throughout, so this may reflect that haplotype's assembly rather than separate TE histories.") \ #text(size: 7.5pt, fill: rgb("#718096"), "TE split >= 2 on 5/8 chromosomes (median 2.17); absolute te_marker_fraction 0.4445 (reference only)")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.") \ #text(size: 7.5pt, fill: rgb("#718096"), "0 split / 0 tetrasomic-like chromosomes; 0 regional split(s)")],
))
#card("ddHypPerf1", "Hypericum perforatum", "2n=32 (x=8)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "4 haplotype copies of each of 8 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (4 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "One copy apart on most chromosomes, changing haplotype between chromosomes: AAAB-like (one divergent genome copy).") \ #text(size: 7.5pt, fill: rgb("#718096"), "8 chromosome numbers assessed: 2 split into lineages, 2 tetrasomic-like, 4 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Repeat history tracks the lineages on several chromosomes: separate TE histories in the split copies.") \ #text(size: 7.5pt, fill: rgb("#718096"), "TE split >= 2 on 2/8 chromosomes (median 1.69); absolute te_marker_fraction 0.4078 (reference only)")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Likely under way: some chromosomes have split into lineages while others stay tetrasomic-like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "2 split / 2 tetrasomic-like chromosomes; 1 regional split(s)")],
))
#card("ddLepDrab1", "Lepidium draba", "2n=64 (octoploid, Europe)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "4 haplotype copies of each of 16 chromosome numbers; the numbers form sets of 2 (8 groups of mostly 2 chromosome numbers), so x ≈ 8 and up to 8x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (4 per number); 8 groups of mostly 2 chromosome numbers (genome partition z = 18.8); homeolog distance 0.069 vs unrelated 0.143")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Mixed: tetrasomic-like and split chromosomes in one genome (see rediploidization).") \ #text(size: 7.5pt, fill: rgb("#718096"), "16 chromosome numbers assessed: 1 split into lineages, 8 tetrasomic-like, 6 one divergent copy, 1 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Repeat history tracks the lineages on 1 chromosome(s) only.") \ #text(size: 7.5pt, fill: rgb("#718096"), "TE split >= 2 on 1/16 chromosomes (median 1.25); absolute te_marker_fraction 0.5465 (reference only)")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Little sign: 1 chromosome(s) partly split among tetrasomic-like ones.") \ #text(size: 7.5pt, fill: rgb("#718096"), "1 split / 8 tetrasomic-like chromosomes; 1 regional split(s); pair-depth CV 0.06")],
))
#card("ddMalSylv1", "Malva sylvestris", "", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 21 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable: two haplotypes and no duplicated sets to compare. Diploid-like as assembled.") \ #text(size: 7.5pt, fill: rgb("#718096"), "no homeolog pairs, no genome partition")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.1346")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("ddPopNigr1", "Populus nigra", "", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly: only one usable haplotype (19 chromosome numbers).") \ #text(size: 7.5pt, fill: rgb("#718096"), "no duplicated sets of chromosome numbers detected")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.") \ #text(size: 7.5pt, fill: rgb("#718096"), "fewer than three copies and nothing to pool")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "TE markers not run for this species.")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("ddSalCine1", "Salix cinerea", "", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly: only one usable haplotype (18 chromosome numbers).") \ #text(size: 7.5pt, fill: rgb("#718096"), "no duplicated sets of chromosome numbers detected")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.") \ #text(size: 7.5pt, fill: rgb("#718096"), "fewer than three copies and nothing to pool")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "TE markers not run for this species.")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("ddSalPent1", "Salix pentandra", "not directly stated", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 38 chromosome numbers; the numbers form sets of 2 (19 groups of mostly 2 chromosome numbers), so x ≈ 19 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 19 groups of mostly 2 chromosome numbers (genome partition z = 47.2); homeolog distance 0.075 vs unrelated 0.148")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.04). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "38 chromosome numbers assessed: 38 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.2000")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.04")],
))
#card("ddSalTria1", "Salix triandra", "haploid n=19 or n=22 (diploid) per a 1924 source -- no modern tripl...", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "3 haplotype copies of each of 19 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (3 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Auto-like (tetrasomic-like): on most chromosomes all copies are about equally close.") \ #text(size: 7.5pt, fill: rgb("#718096"), "19 chromosome numbers assessed: 0 split into lineages, 13 tetrasomic-like, 6 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Repeat history tracks the lineages on 2 chromosome(s) only.") \ #text(size: 7.5pt, fill: rgb("#718096"), "TE split >= 2 on 2/19 chromosomes (median 1.22); absolute te_marker_fraction 0.2473 (reference only)")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "No sign yet: copies interchangeable throughout.") \ #text(size: 7.5pt, fill: rgb("#718096"), "0 split / 13 tetrasomic-like chromosomes; 0 regional split(s); pair-depth CV 0.02")],
))
#card("dmRanRepe1", "Ranunculus repens", "", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 16 chromosome numbers; the numbers form sets of 2 (no accepted pairs, but a balanced two-group partition), so x ≈ 8 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); no accepted pairs, but a balanced two-group partition (8 vs 8, z = 10.9)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from a genome-wide partition (no accepted pairs). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "16 chromosome numbers assessed: 16 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.0658")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("drAriEdul1", "Aria edulis", "2n=34 (x=17); base number matches our 17 chromosome numbers exactly...", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "4 haplotype copies of each of 17 chromosome numbers; the numbers form sets of 2 (8 groups of mostly 2 chromosome numbers), so x ≈ 8 and up to 8x relative to x; the sets are nearly as diverged as unrelated chromosomes, so they may be an old (paleo) duplication.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (4 per number); 8 groups of mostly 2 chromosome numbers (genome partition z = 10.0); homeolog distance 0.099 vs unrelated 0.109")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Mixed: tetrasomic-like and split chromosomes in one genome (see rediploidization).") \ #text(size: 7.5pt, fill: rgb("#718096"), "17 chromosome numbers assessed: 3 split into lineages, 3 tetrasomic-like, 4 one divergent copy, 7 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Repeat content differs between the split copies on several chromosomes, but the split isolates the same odd haplotype throughout, so this may reflect that haplotype's assembly rather than separate TE histories.") \ #text(size: 7.5pt, fill: rgb("#718096"), "TE split >= 2 on 6/17 chromosomes (median 1.47); absolute te_marker_fraction 0.2194 (reference only)")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Likely under way: some chromosomes have split into lineages while others stay tetrasomic-like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "3 split / 3 tetrasomic-like chromosomes; 5 regional split(s); pair-depth CV 0.03")],
))
#card("drIngLaur1", "Inga laurina", "", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly: only one usable haplotype (13 chromosome numbers).") \ #text(size: 7.5pt, fill: rgb("#718096"), "no duplicated sets of chromosome numbers detected")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.") \ #text(size: 7.5pt, fill: rgb("#718096"), "fewer than three copies and nothing to pool")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "TE markers not run for this species.")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("drLytSali1", "Lythrum salicaria", "unspecified", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "4 haplotype copies of each of 15 chromosome numbers; the numbers form sets of 3 (5 groups of mostly 3 chromosome numbers), so x ≈ 5 and up to 12x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (4 per number); 5 groups of mostly 3 chromosome numbers (genome partition z = 10.5); homeolog distance 0.097 vs unrelated 0.125")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Auto-like (tetrasomic-like): on most chromosomes all copies are about equally close.") \ #text(size: 7.5pt, fill: rgb("#718096"), "15 chromosome numbers assessed: 0 split into lineages, 13 tetrasomic-like, 1 one divergent copy, 1 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Repeat history tracks the lineages on 1 chromosome(s) only.") \ #text(size: 7.5pt, fill: rgb("#718096"), "TE split >= 2 on 1/15 chromosomes (median 1.05); absolute te_marker_fraction 0.3070 (reference only)")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "No sign yet: copies interchangeable throughout.") \ #text(size: 7.5pt, fill: rgb("#718096"), "0 split / 13 tetrasomic-like chromosomes; 1 regional split(s); pair-depth CV 0.05")],
))
#card("drMyrSpic1", "Myriophyllum spicatum", "2n=42 (x=7)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 21 chromosome numbers; the numbers form sets of 3 (7 groups of mostly 3 chromosome numbers), so x ≈ 7 and up to 6x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 7 groups of mostly 3 chromosome numbers (genome partition z = 24.7); homeolog distance 0.061 vs unrelated 0.135")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.33). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "16 chromosome numbers assessed: 16 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.3590")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Possibly: ancient pairs diverged to different depths (asynchronous resolution).") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.33")],
))
#card("drMyrVert1", "Myriophyllum verticillatum", "2n=28", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 14 chromosome numbers; the numbers form sets of 2 (7 groups of mostly 2 chromosome numbers), so x ≈ 7 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 7 groups of mostly 2 chromosome numbers (genome partition z = 11.6); homeolog distance 0.098 vs unrelated 0.149")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.03). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "14 chromosome numbers assessed: 14 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.5213")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.03")],
))
#card("drRosSpin1", "Rosa spinosissima", "2n=14 (2026 genome paper) vs 2n=28 (majority of older sources) -- d...", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 14 chromosome numbers; the numbers form sets of 2 (7 groups of mostly 2 chromosome numbers), so x ≈ 7 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 7 groups of mostly 2 chromosome numbers (genome partition z = 14.0); homeolog distance 0.054 vs unrelated 0.107")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.03). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "14 chromosome numbers assessed: 14 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.1215")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.03")],
))
#card("drSorDevo1", "Sorbus devoniensis", "2n=68", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 34 chromosome numbers; the numbers form sets of 2 (17 groups of mostly 2 chromosome numbers), so x ≈ 17 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 17 groups of mostly 2 chromosome numbers (genome partition z = 42.5); homeolog distance 0.049 vs unrelated 0.110")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.03). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "34 chromosome numbers assessed: 34 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.1528")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.03")],
))
#card("drTriDubi3", "Trifolium dubium", "", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly: only one usable haplotype (15 chromosome numbers). The numbers do form duplicated sets (7 homeolog pairs covering 93% of numbers).") \ #text(size: 7.5pt, fill: rgb("#718096"), "7 homeolog pairs covering 93% of numbers")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.") \ #text(size: 7.5pt, fill: rgb("#718096"), "fewer than three copies and nothing to pool")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "TE markers not run for this species.")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.09")],
))
#card("drTriRepe1", "Trifolium repens", "2n=32", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 16 chromosome numbers; the numbers form sets of 2 (8 groups of mostly 2 chromosome numbers), so x ≈ 8 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 8 groups of mostly 2 chromosome numbers (genome partition z = 15.3); homeolog distance 0.061 vs unrelated 0.105")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.03). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "16 chromosome numbers assessed: 16 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.1692")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.03")],
))
#card("drUrtDioi1", "Urtica dioica", "", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly: only one usable haplotype (13 chromosome numbers).") \ #text(size: 7.5pt, fill: rgb("#718096"), "no duplicated sets of chromosome numbers detected")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.") \ #text(size: 7.5pt, fill: rgb("#718096"), "fewer than three copies and nothing to pool")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "TE markers not run for this species.")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("laPotCris1", "Potamogeton crispus", "2n=50/52/78/84 (multiple conflicting reports)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 26 chromosome numbers; the numbers form sets of 2 (12 groups of mostly 2 chromosome numbers), so x ≈ 12 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 12 groups of mostly 2 chromosome numbers (genome partition z = 18.1); homeolog distance 0.098 vs unrelated 0.130")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.08). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "24 chromosome numbers assessed: 24 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.3356")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.08")],
))
#card("laPotLuce1", "Potamogeton lucens", "2n=52", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 26 chromosome numbers; the numbers form sets of 2 (10 groups of mostly 2 chromosome numbers), so x ≈ 10 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 10 groups of mostly 2 chromosome numbers (genome partition z = 15.0); homeolog distance 0.080 vs unrelated 0.117")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.11). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "24 chromosome numbers assessed: 24 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.2458")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.11")],
))
#card("laPotNata1", "Potamogeton natans", "2n=52 (also 2n=104 reported)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 25 chromosome numbers; the numbers form sets of 2 (12 groups of mostly 2 chromosome numbers), so x ≈ 12 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 12 groups of mostly 2 chromosome numbers (genome partition z = 20.0); homeolog distance 0.077 vs unrelated 0.122")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.13). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "24 chromosome numbers assessed: 24 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.2498")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.13")],
))
#card("laPotNodo1", "Potamogeton nodosus", "2n=52", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 26 chromosome numbers; the numbers form sets of 2 (13 groups of mostly 2 chromosome numbers), so x ≈ 13 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 13 groups of mostly 2 chromosome numbers (genome partition z = 19.4); homeolog distance 0.094 vs unrelated 0.124")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.09). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "26 chromosome numbers assessed: 26 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.2838")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.09")],
))
#card("laPotPerf1", "Potamogeton perfoliatus", "2n=52", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 26 chromosome numbers; the numbers form sets of 2 (13 groups of mostly 2 chromosome numbers), so x ≈ 13 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 13 groups of mostly 2 chromosome numbers (genome partition z = 19.3); homeolog distance 0.088 vs unrelated 0.120")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.08). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "26 chromosome numbers assessed: 26 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.3552")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.08")],
))
#card("llColAutu1", "Colchicum autumnale", "2n=36", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 51 chromosome numbers; the numbers form sets of 2 (24 homeolog pairs covering 94% of numbers), so x ≈ 26 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 24 homeolog pairs covering 94% of numbers; homeolog distance 0.069 vs unrelated 0.112")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Allo-like (disomic-like): the duplicated sets do not interchange, from homeolog pairs (pair-depth CV 0.05). This is also what a long-rediploidized autopolyploid looks like.") \ #text(size: 7.5pt, fill: rgb("#718096"), "48 chromosome numbers assessed: 48 split into lineages, 0 tetrasomic-like, 0 one divergent copy, 0 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.0500")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Not testable along chromosomes with two copies; ancient pairs are synchronous.") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.05")],
))
#card("lpElePalu1", "Eleocharis palustris", "", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 19 chromosome numbers; the numbers form sets of 2 (9 groups of mostly 2 chromosome numbers), so x ≈ 9 and up to 4x relative to x.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number); 9 groups of mostly 2 chromosome numbers (genome partition z = 22.8); homeolog distance 0.020 vs unrelated 0.091")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Mixed: some duplicated sets look interchangeable, others separate.") \ #text(size: 7.5pt, fill: rgb("#718096"), "18 chromosome numbers assessed: 4 split into lineages, 8 tetrasomic-like, 2 one divergent copy, 4 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.0830")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Possibly: ancient pairs diverged to different depths (asynchronous resolution).") \ #text(size: 7.5pt, fill: rgb("#718096"), "pair-depth CV 0.56")],
))
#card("lpTriTurg1_A", "Triticum turgidum, A subgenome", "2n = 4x = 28 (AABB); A subgenome run on its own", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 7 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable: two haplotypes and no duplicated sets to compare. Diploid-like as assembled.") \ #text(size: 7.5pt, fill: rgb("#718096"), "no homeolog pairs, no genome partition")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.0122")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("lpTriTurg1_B", "Triticum turgidum, B subgenome", "2n = 4x = 28 (AABB); B subgenome run on its own", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "2 haplotype copies of each of 7 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (2 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable: two haplotypes and no duplicated sets to compare. Diploid-like as assembled.") \ #text(size: 7.5pt, fill: rgb("#718096"), "no homeolog pairs, no genome partition")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Only the absolute marker fraction is available (two copies per number); it does not separate diploid, auto- and allopolyploid, so no reading is made from it.") \ #text(size: 7.5pt, fill: rgb("#718096"), "te_marker_fraction mean 0.0152")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("not assessable", "#a0aec0")],
  [#text(size: 8.8pt, "Not assessable from this assembly.")],
))
#card("SchCurv1", "Schizothorax curvilabiatus", "4n = 98 (Xie et al., 2026)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "4 haplotype copies of each of 25 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (4 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Mixed: tetrasomic-like and split chromosomes in one genome (see rediploidization).") \ #text(size: 7.5pt, fill: rgb("#718096"), "25 chromosome numbers assessed: 4 split into lineages, 17 tetrasomic-like, 2 one divergent copy, 2 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("low", "#c05621")],
  [#text(size: 8.8pt, "Repeat history tracks the lineages on 4 chromosome(s) only.") \ #text(size: 7.5pt, fill: rgb("#718096"), "TE split >= 2 on 4/24 chromosomes (median 1.10); absolute te_marker_fraction 0.2089 (reference only)")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Yes: 1 chromosome fusion(s) between copies, which separate fused and unfused lineages (the snow carp mechanism).") \ #text(size: 7.5pt, fill: rgb("#718096"), "1 fusion(s): chr19+chr22; 4 split / 17 tetrasomic-like chromosomes; 4 regional split(s); pair-depth CV 0.15")],
))
#card("SchYoun1", "Schizopygopsis younghusbandi", "4n = 90 (Xie et al., 2026)", (
  [#text(size: 8.5pt, weight: "bold", "Ploidy") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "4 haplotype copies of each of 25 chromosome numbers; no older duplicated sets detected.") \ #text(size: 7.5pt, fill: rgb("#718096"), "copies from the assembly (4 per number)")],
  [#text(size: 8.5pt, weight: "bold", "Auto- or allo-like") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Mixed: tetrasomic-like and split chromosomes in one genome (see rediploidization).") \ #text(size: 7.5pt, fill: rgb("#718096"), "25 chromosome numbers assessed: 10 split into lineages, 14 tetrasomic-like, 0 one divergent copy, 1 candidate")],
  [#text(size: 8.5pt, weight: "bold", "TE markers") \ #badge("medium", "#b7791f")],
  [#text(size: 8.8pt, "Repeat history does not track the copies' lineages (no within-genome TE contrast).") \ #text(size: 7.5pt, fill: rgb("#718096"), "TE split >= 2 on 0/15 chromosomes (median 1.06); absolute te_marker_fraction 0.2227 (reference only)")],
  [#text(size: 8.5pt, weight: "bold", "Rediploidization") \ #badge("high", "#2f855a")],
  [#text(size: 8.8pt, "Yes: 5 chromosome fusion(s) between copies, which separate fused and unfused lineages (the snow carp mechanism).") \ #text(size: 7.5pt, fill: rgb("#718096"), "5 fusion(s): chr04+chr15, chr08+chr16, chr11+chr14, chr19+chr22, chr20+chr23; 10 split / 14 tetrasomic-like chromosomes; 1 regional split(s)")],
))
